-- liquibase formatted sql

--changeSet konstantin:1
CREATE TABLE adoptive_parent (
                       id bigint generated by default as identity primary key,
                       chat_id bigint,
                       name text,
                       phone_number bigint,
                       address text,
                       message text
);

--changeSet stepan:2
CREATE TABLE report (
                       id bigint generated by default as identity primary key,
                       parent_id bigint,
                       pet_id bigint,
                       photo bytea,
                       diet text,
                       health text,
                       behavior text,
                       report_date DATE
);

--changeSet anatoliy:3
CREATE TABLE pet (
                        id bigint generated by default as identity primary key,
                        parent_id bigint,
                        type text,
                        name text,
                        age int,
                        description text
);

--changeSet anatoliy:4
INSERT INTO pet VALUES ('1',null, 'cat', 'тузик', 12, 'домашний котик');
INSERT INTO pet VALUES ('2',null, 'cat', 'мурзик', 12, 'домашний котик');
INSERT INTO pet VALUES ('3',null, 'dog', 'шарик', 12, 'домашний пес');
INSERT INTO pet VALUES ('4',null, 'dog', 'чара', 12, 'домашняя собака');
INSERT INTO pet VALUES ('5',null, 'cat', 'бегемот', 12, 'домашний котик');

--changeSet konstantin:5
INSERT INTO adoptive_parent VALUES ('1', 641625801, 'Jack', 89109999999, 'London, Queen st. 10', 'i wanna котик');
INSERT INTO pet VALUES ('6', 1, 'cat', 'тузик', 12, 'домашний котик');
INSERT INTO pet VALUES ('7', 1, 'cat', 'мурзик', 12, 'домашний котик');
INSERT INTO pet VALUES ('8', 1, 'dog', 'шарик', 12, 'домашний пес');
